<?php

namespace AppBundle\Repository;

/**
 * tasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tasksRepository extends \Doctrine\ORM\EntityRepository
{
}
