<?php

namespace AppBundle\Repository;

/**
 * unitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class unitsRepository extends \Doctrine\ORM\EntityRepository
{
}
