# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        webservice:
            id: app.player_provider


    encoders:
        AppBundle\Entity\Player:
            id: sha256salted_encoder

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /
            logout:
                path:   /logout
                target: /


    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/carte, roles: ROLE_USER}
        - { path: ^/construction, roles: ROLE_USER}
        - { path: ^/unite, roles: ROLE_USER}
        - { path: ^/messagerie, roles: ROLE_USER}
        - { path: ^/accueil, roles: ROLE_USER}
        - { path: ^/createPerso, roles: ROLE_USER}
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
